image: atlassian/default-image:3

pipelines:
  pull-requests:
    '**':
    - step:
        name: Build the code
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn clean package
        artifacts:
          - target/hello-shiftleft-0.0.1.jar
          - sl-analysis.sh
          - shiftleft.yml
    - step:
        name: Install ShiftLeft and dependencies
        image: shiftleft/inspect
        script:
          - sh sl-analysis.sh