image: maven:3.3.9-jdk-8

pipelines:
  pull-requests:
    '**':
    - step:
        name: Build the code
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          - mvn clean package
        artifacts:
          - target/hello-shiftleft-0.0.1.jar
          - sl-analysis.sh
          - shiftleft.yml
    - step:
        name: Install ShiftLeft and dependencies
        script:
          - curl https://cdn.shiftleft.io/download/sl >/usr/local/bin/sl && chmod a+rx /usr/local/bin/sl
          - apt-get install jq -y
    - step: Run code analysis and build rules check
      name: 
          - sh sl-analysis.sh