pipelines:
  pull-requests:
    '**':
    - step:
        name: Build the code
        caches:
          - maven
        script:
          - mvn clean package
        artifacts:
          - target/hello-shiftleft-0.0.1.jar
          - sl-analysis.sh
          - shiftleft.yml
    - step:
        name: Run ShiftLeft
        image: shiftleft/inspect
        script:
          - sh sl-analysis.sh