name: Analyze with SCA Demo with NG SAST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ngsast-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Download the ShiftLeft CLI and set permissions
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    
    - name: Set up Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    
    - name: Package with Maven
      run: mvn clean package

    - name: Download the ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: Analyze app with NG SAST
      run: ${GITHUB_WORKSPACE}/sl analyze --app dec-demo --wait --force --remediation-config suppress.yaml --no-diagnostic target/hello-shiftleft-0.0.1.jar --java
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}

  build-rules:
    runs-on: ubuntu-20.04
    needs: ngsast-build
    steps:
      - uses: actions/checkout@v2
      - name: Download ShiftLeft CLI
        run: |
          curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
      - name: Check results against build rules
        run: ${GITHUB_WORKSPACE}/sl check-analysis --app sca-demo --config ./shiftleft.yml --v2
        env:
          SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
