name: Analyze with SCA Demo with NG SAST

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ngsast-build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    
    - name: Download the ShiftLeft CLI and set permissions
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl
    
    - name: Set up Java
      uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    
    - name: Package with Maven
      run: mvn clean package

    - name: Download the ShiftLeft CLI
      run: |
        curl https://cdn.shiftleft.io/download/sl > ${GITHUB_WORKSPACE}/sl && chmod a+rx ${GITHUB_WORKSPACE}/sl

    - name: Analyze app with NG SAST
      run: ${GITHUB_WORKSPACE}/sl analyze --app sca-demo --wait --force --no-diagnostic /Users/katie/sample-apps/shiftleft-java-example/target/hello-shiftleft-0.0.1.jar --java
      env:
        SHIFTLEFT_ACCESS_TOKEN: ${{ secrets.SHIFTLEFT_ACCESS_TOKEN }}
